### ISSUE TITLE
"rake demo" gives java.lang.UnsupportedClassVersionError: Bad version number in .class file

### ISSUE THREAD

**Issue by cbrunnkvist** [typekit/webfontloader#6]
I'm using OSX 10.5 with bundled Java 1.5.0_22 and I get this error when trying to "rake demo".

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: Bad version number in .class file
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:676)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:56)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:317)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:280)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
  at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:375)
bin/webfontloader-demos:22:in `read': No such file or directory - target/webfont.js (Errno::ENOENT)
  from bin/webfontloader-demos:22
  from ~/.rvm/rubies/ruby-1.8.6-p383/lib/ruby/1.8/optparse.rb:1265:in `call'
  from ~/.rvm/rubies/ruby-1.8.6-p383/lib/ruby/1.8/optparse.rb:1265:in `parse_in_order'
  from ~/.rvm/rubies/ruby-1.8.6-p383/lib/ruby/1.8/optparse.rb:1252:in `catch'
  from ~/.rvm/rubies/ruby-1.8.6-p383/lib/ruby/1.8/optparse.rb:1252:in `parse_in_order'
  from ~/.rvm/rubies/ruby-1.8.6-p383/lib/ruby/1.8/optparse.rb:1246:in `order!'
  from ~/.rvm/rubies/ruby-1.8.6-p383/lib/ruby/1.8/optparse.rb:1337:in `permute!'
  from ~/.rvm/rubies/ruby-1.8.6-p383/lib/ruby/1.8/optparse.rb:1358:in `parse!'
  from ~/.rvm/gems/ruby-1.8.6-p383/gems/vegas-0.1.6/lib/vegas/runner.rb:278:in `define_options'
  from ~/.rvm/gems/ruby-1.8.6-p383/gems/vegas-0.1.6/lib/vegas/runner.rb:39:in `initialize'
  from bin/webfontloader-demos:20:in `new'
  from bin/webfontloader-demos:20
```

**Comment by sylvain-galineau** [comment]
FWIW, I also ran into the same issue 5 years later. This has to do with the JDK version Clojure expects vs. what OSX ships with. As of right now, one needs to install JDK7. In addition, the instructions in CONTRIBUTING.md imply PhantomJS to be only needed to run tests in headless WebKit. The default rake build fails if PhantomJS is not installed though.
